services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: crud-mysql-dev
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: crud_api
      MYSQL_USER: crud_user
      MYSQL_PASSWORD: crud_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_dev_data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # phpMyAdmin (Database Management)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: crud-phpmyadmin-dev
    platform: linux/amd64
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: crud_user
      PMA_PASSWORD: crud_password
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8082:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - app-network

volumes:
  mysql_dev_data:

networks:
  app-network:
    driver: bridge